name: "ContextCore Build & Test (macOS)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-15
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Set uv path
      run: echo "UV_PATH=$(which uv)" >> "$GITHUB_ENV"
    - uses: actions/cache@v4
      with:
        path: ./ContextCore/.build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: "16.3"
    - name: Run tests
      working-directory: ./ContextCore
      run: |
        set -o pipefail
        swift test --verbose --no-parallel 2>&1 | xcbeautify --renderer github-actions
      env:
        NSUnbufferedIO: YES
